language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
sudo: required
services:
- docker
notifications:
  email:
  - bilalwahla@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: oFVXxwYnEfnxbVUf1PMYKZvvXtB5Yf30sWwM3H9130mGNR9EZc7SPOBjhX0HuDR21BLYP9GeXjQRwIrbe6LZOsxqn1tXHRm2LdDbWG/KdxmzkwtUvA8Y4lJmBuG9pBw9z/cZItNiv7Og1FpYpSdQjOXJla83wdGXvsXEZQk1wcZvrWDwelVqv6i088/q4UniCgWW8hVuwgmIzVj/2LS8wB4bhqmoHEu8IfM+bc6ynX81gbDmmoCDjASDBpaGeKE+vyM9oYw4TjIKurqMu1oDPVS74k1GMW6y6lXNbT4eUDOyNPyuT7sebfSDfgZ8ZgLiT/duZGKloZpD59nLuT5MsQd5aF4Sx9QoQsv8WyemjaJ+0Ca2rbi7wFESo+AMVb6gdTyi9PzyVps+FIEfpWtPg2s6zR1PjRcNbzLHnj69TPBmWfor7VVCMijQTkVO8RFeYYKzCrQFMMPJvxjGq8Ld6hDRvTeWkXKMPZE0aU//l3ywk/zOmwTAnKH8ZkNbrbXiUmPG8z4VfgawTssi32kzkgdhJEsgFVJBose1+NJG2iiMHCgwZK45hyaqT4IQvCNfdadOIMK/FLSgYzIzuQu7odFI7zTRVdv+zUveybv6bR/aoXrYjNTLONd7VPf+iwMQvPYaEWCQqDwjr95ASHS3exQQGYTGVeVXLLwcKQy3BUA=
  - secure: b1Jnjb54gn5xe+sLGT3CbX9plQymHze8oNuetzrnwSWlJ3IYl3NnqLob1YI2UTBL4gGqrS5ac1f17MBBHNoOZMNd5arWQ9u7brWGsr+eTlDD6xN1WxNAJT36oY2xMpf6eqHofcn/1xBDkNZiUhj+aukP42NiuAza2Xm5+PZn5LeA6ybnfGcxrYfXChnruU1+2A8KmgSLv2VkrgXsluLDhDbJyC2j0KrU0qcpoW4fU4lVEXMbA8PSYPC4F+rGkGALFBoeZXDt+Y/HAnWJxiNU2zq/t0cEjZlAV3SXhHDgjSQYAg9vWMOZtzLFUarjcvQRh82AYPD19VOi6o9N0bhcX1m8IrPnwp880ZwdOhwp8vFkvmnwtmI3wymfeNVxv2pOQRRzTTEqYyK8znkMCXDwIGowYchluxacd8OfY+qQP8lukbtwfPnRCZfuSUF01acx/ay6Ebjz3RFsOjKlpOjRIpJZIeE3dM+dX2n2DSwkswAqaLjEAXe3xXFKaiG16vr9qv9zZrzXjwgUSOM+TVKCwVQ99pfEGBGTvgLuGWuqbzEDldjHq0qczRP65TD0DDPcl0OvowKJ7Xw9o6hy2hUyCR4DEy156bH+l72z5yG4yYlW2Amm3N7J2pqaADZ7m5IZPHLp+kZopHBKsTi1detSR18l3iV9GEjpUfXqvbyXcrI=
  - secure: LVmsGk4HjWrg+BZyDkT48PmeIpil0ZAlz3C3poEoro4T0DhBd+OwaFepCXWpkyNSZHOHGhEmUsJSLIUFQj1gO6RbR1pn5aWHaDfB6l/HFVfSl2P5qOzMUsCP0EvrCXjCdIvFq0j8VFrlB06oBKXv+5aEw3p2VJCxvVh5ZeE85WSl+MZvqtjycqiXxyGtm0C0/BRWIVNYCPAdzgVfSH1frvIpyDwQ0vi/tmbrNJu4ICbJrm7xrpEwawALE+NZfYlO8s7GSrcMvsOOL4yAUp5tlrK8KJ5qkQmBq40uslEeQXVgWaomD/hFp0npjf/gYrCqetiJzPo7/6v8zhwXyHi90wcaufhxWdztYfNMP3undoLe/EyKgBxi5mJf6TuVEtQLnxiO7S6HF/fvUoiOHbPc8iXA+UR5MBqznIrZU0UIZovIlr70ZINA1057IVJK3PP//ZXf+kv+URP3H2uGsjTRQA724gZzel80XymzigvmGX0d2tV+Ab0UHoOm3KbFshBF2ttoyh8waV0TyOL/tPRwoM/hoDFauoCu9xQEZWETXyQ3+gTMOXBhokWnnFf9skf7pLSu4sI7GwM82C18HQsx0wNBR6SOFJVGaVFvEBkaXcJskugwDr/oppcazd0eEVvHVkF7IzvjPhNwJpTicMmAGlBjYYD+zbKAva/0Y+hQ0PM=
  - secure: A7A/n0VmKfnXVWfJ6xbCAjl1UADXYRUptpzkIa/2yR6Le/ULSNRs4NTc4w9YOSV3D11SnGGb64TxpRXChcNJnebJ2w+iyih9KGNC1L2lTLezgTIDs3X/1wp2aEeM/I3bgB/BgNj2bi2NjwPT9tHvv+XQS1Vl2CbbE4/LASKWY7JUPS1T2aZKAlt2yBAV9KHrbaN6u3dJkMj3AcfyHNfThb0M/36z2f3Lp0uX7oE1UWDYbfOHwW23vkv1PRF88GojDSUqpEmekzqgJgjUqIsDy9/DRr7NgFTlYJ/F0MIbm9S+vo47BLmGzalCY7jeIkjQkTqMvSv4wy33GNQjIfk6yFIOjjomb9MK4It/TDxr07dxDFQXoav4x7gcJ4+4A/5z27ys+EbZRyugm4Rg1KklgTBmqborv9sGDCZO2LwoFqZ8mfLXSCzL5aJK/4eMzvXjTIYTI2PfUwjnN/dDLMa5gyLBuIZFqvEzA838Ai55YKzI2IYETVNxCFa/RZk87KrN+z4mWzJM8hnWA2uUA+s2Rc5Lf95DMjL3SSfdG07c66B1u/UsCulYzNpHlDzo2CkcTz/VTWJ77XW7inn1ObEecyy62fJvyAftsBAzeM9dWrXwpVc2qQcVvPqMzbOeCjxjqZwHXO75Xivznnz1hEDtJPUJBO33V06P1g7c1I+HGX4=
  - secure: GlPviwJ2Pyd70yNLHE7Mmknz0oBekfcIg0kL5Awtz5zKXBjnAgxCwyM9Np2nwwmLoQXpv5AJ/DXsaebi/Ae1xqP7SZ5bOlq/IOCNABOgGbg5mGoe7un9UjJ6k/tPuQLE8QUrU3k9e6hB/2niDlvQRJw0UcK4kIkgI1QLMqip2ONsRUxnLB1zsno0fFKgPgbIvQ9JQoleLdZ0BZkCt4f+TTBZPt5MpkarGNRNLK0sAPksJe3lvl0fs2AjC7Le42KONOY5k5ckrU/a5mMkYwD2J7XsDbG1bGBG66EpgprxSB0WZkbiiMpLj6+3IKYhZg7hbcCipJQgnip1P+fY+34g+eSFS3M/RHmuWjf/rQDjAg9cTRYzVY+Ec+KNFWHJ1WAzEmVCaJIIgMX9Gsf6ID669lTcgrF7y5hSafQTGEeMVYNAxENaIxVkRw7GK1dtSN3myJJw2zwH16m/UPFvPSOm8lYohG99FzAvtAR+F5lmdXmMQ0biml8QK4ZuqfoHyJhEJl5sxCOa2IZTecNgqR6fn0akCLRa4VSUxIyFe+mbhIcTrwH/jtyKeRA1nIq1d6EhV1kWN8qy/dHqA1gb1SVLQSRLtvPpVwNJew3DgpO6ONsTSEdK4s7zAit4U5BF4Vyn5RXlPAfX6D8Whn4UWx6/ET7U0RG6YToHLku8Ip2EsCs=
before_install:
- gem install travis -v 1.8.8 --no-rdoc --no-ri
- sudo curl -k -o /usr/local/bin/ecs-cli https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest
- sudo chmod +x /usr/local/bin/ecs-cli
- export BUILD_NAME=microservices-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
- sh travis_scripts/deploy_to_amazon_ecs.sh
