eurekaserver:
   image:   bilalwahla/df-eurekasvr:${BUILD_NAME}
   mem_limit: 1073741824
   ports:
      - "8761:8761"
configserver:
  image: bilalwahla/df-confsvr:${BUILD_NAME}
  mem_limit: 1000000000
  ports:
    - "8888:8888"
  links:
    - "eurekaserver:eurekaserver"
  environment:
     EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
     ENCRYPT_KEY:       "IMSYMMETRIC"
zipkin:
  image: bilalwahla/df-zipkinsvr:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "9411:9411"
zuulserver:
  image: bilalwahla/df-zuulsvr:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "5555:5555"
  links:
    - "eurekaserver:eurekaserver"
    - "configserver:configserver"
  environment:
    PROFILE: "default"
    SERVER_PORT: "5555"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    ZIPKIN_URI: "http://zipkin:9411"
licensingservice:
  image: bilalwahla/df-licensing-service:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8080:8080"
  links:
    - "configserver:configserver"
    - "eurekaserver:eurekaserver"
    - "zuulserver:zuulserver"
    - "kafkaserver:kafkaserver"
  environment:
    PROFILE: "aws-dev"
    SERVER_PORT: "8080"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    ZIPKIN_URI: "http://zipkin:9411"
    KAFKASERVER_URI: "kafkaserver"
    ZKSERVER_URI: "kafkaserver"
    ENCRYPT_KEY:       "IMSYMMETRIC"
organizationservice:
  image: bilalwahla/df-organization-service:${BUILD_NAME}
  mem_limit: 1073741824
  ports:
    - "8085:8085"
  links:
    - "configserver:configserver"
    - "eurekaserver:eurekaserver"
    - "zuulserver:zuulserver"
    - "kafkaserver:kafkaserver"
  environment:
    PROFILE: "aws-dev"
    SERVER_PORT: "8085"
    CONFIGSERVER_URI: "http://configserver:8888"
    EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
    ZIPKIN_URI: "http://zipkin:9411"
    KAFKASERVER_URI: "kafkaserver"
    ZKSERVER_URI: "kafkaserver"
    ENCRYPT_KEY:       "IMSYMMETRIC"
kafkaserver:
  image: spotify/kafka
  mem_limit: 1073741824
  ports:
    - 2181:2181
    - 9092:9092
logspout:
  image: gliderlabs/logspout
  command: syslog://logs6.papertrailapp.com:16878
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
